### ISSUE TITLE
not downloading images from public/tiles/zones/10125/X.png

### ISSUE THREAD

**Issue by juddisjudd** [ssttevee/papunika-map-mirror#2]
Does not seem to make the "zones" folder with the id folder underneath with images for the locations.

Example image that is accessible:
https://papunika.com/map/public/tiles/zones/10125/2_0_0.png

**Comment by ssttevee** [comment]
This should be fixed in 534ea5b51df5c694597b0eef4b323aae11e0db1f. I actually just forgot to push my changes after the first commit. 🙈
